# Dependabot will run on day 8 of each month at 02:07 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "7 2 8 * *"
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "7 2 8 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "7 2 8 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/src-admin"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "7 2 8 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/src-admin-tab"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "7 2 8 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/src-widgets"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "7 2 8 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/src-admin-v1"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "7 2 8 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"
